# Generated by Django 4.1.7 on 2024-02-21 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookGenres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=100, verbose_name="Название жанра"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("VK", models.CharField(default="", max_length=300, verbose_name="VK")),
                (
                    "Instagram",
                    models.CharField(
                        default="", max_length=300, verbose_name="Instagram"
                    ),
                ),
                (
                    "AboutMe",
                    models.TextField(default="", max_length=700, verbose_name="О себе"),
                ),
                ("bookGenres", models.ManyToManyField(to="accounts.bookgenres")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
