# Generated by Django 4.1.7 on 2024-02-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="Telegram",
            field=models.CharField(default="", max_length=300, verbose_name="Telegram"),
        ),
    ]
