# Generated by Django 5.0.2 on 2024-03-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdata_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='AboutMe',
            field=models.TextField(blank=True, default='', max_length=700, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Instagram',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Telegram',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='VK',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='VK'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='bookGenres',
            field=models.ManyToManyField(blank=True, to='accounts.bookgenres'),
        ),
    ]
