# Generated by Django 5.0.2 on 2024-03-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userdata_photo_alter_userdata_aboutme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='bookGenres',
        ),
        migrations.DeleteModel(
            name='BookGenres',
        ),
    ]
