# Generated by Django 5.0.2 on 2024-03-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userdata_bookgenres_delete_bookgenres'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bookGenres',
            field=models.ManyToManyField(blank=True, to='main.bookgenres'),
        ),
    ]
