# Generated by Django 5.0.2 on 2024-03-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userdata_bookgenres'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='showLikedBooks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Instagram',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Telegram',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='VK',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='VK'),
        ),
    ]
