# Generated by Django 5.0.2 on 2024-03-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_bookсhapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shortDescription',
            field=models.TextField(default='', max_length=120, verbose_name='Краткое описание сюжета'),
        ),
    ]
