# Generated by Django 5.0.2 on 2024-03-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Тематики'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='', max_length=3500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='shortDescription',
            field=models.TextField(default='', max_length=550, verbose_name='Краткое описание сюжета'),
        ),
    ]
