# Generated by Django 5.0.2 on 2024-03-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_book_topic_likebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likebook',
            name='likeOrNot',
        ),
    ]
