# Generated by Django 5.0.2 on 2024-05-04 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_likebook_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ageLimit',
            field=models.IntegerField(blank=True, default=16, null=True, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookсhapter',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.book'),
        ),
        migrations.AlterField(
            model_name='bookсhapter',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер главы в книге'),
        ),
        migrations.CreateModel(
            name='СommentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время публикации')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='main.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
