# Generated by Django 5.0.2 on 2024-05-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_book_agelimit_alter_book_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='сommentbook',
            old_name='data',
            new_name='date',
        ),
    ]
