name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and git pull on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd ~/Shelf
          git pull
          
          
          # Получаем идентификатор текущего запущенного контейнера
          container_id=$(docker ps -qf "ancestor=shelfapp")
          # Если контейнер существует, останавливаем и удаляем его
          if [ ! -z "$container_id" ]; then
            docker stop $container_id
            docker rm $container_id
          fi
          # Строим новый образ и запускаем контейнер с уникальным именем
          docker build -t shelfapp .
          docker run -d --net=host --name shelfapp shelfapp:latest
