name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Укажите версию Python, которая соответствует вашему проекту

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Git pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd ~/Shelf
          git pull

    - name: Run Django tests
      run: python3 manage.py test

    - name: SSH and git pull on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          container_id=$(docker ps -qf "ancestor=shelfapp")
          if [ ! -z "$container_id" ]; then
            docker stop $container_id
            docker rm $container_id
          fi
          
          docker build -t shelfapp .
          docker run -d --net=host --name shelfapp shelfapp:latest
