name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and git pull on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd ~/Shelf
          git pull
          
          docker build -t shelfapp .
          
          container_id=$(docker ps -qf "ancestor=shelfapp")
          docker stop $container_id || true
          docker rm $container_id || true
          
          docker run --net=host --name shelfapp shelfapp:latest
